### PR TITLE
fix(List): add aria attributes

### LINKED ISSUE #2552: List: Add accessibility in filtering list
### Description

I am using a filtered list controlled by an input field.
However, the input does not have the required ARIA attributes, so screen readers cannot announce the currently active item in the list.
Although users can navigate through the list items using arrow keys, the active option is not properly exposed to assistive technologies.

### Suggested solution

Add the necessary ARIA attributes to the input to correctly describe its relationship with the list and the active item:

role="combobox" — identifies the input as a combobox control

aria-activedescendant — points to the ID of the currently active list item

This ensures that screen readers can correctly announce the active item while navigating the list with the keyboard. 

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [x] Check that there isn't [already an issue](https://github.com/gravity-ui/uikit/issues) that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by PosikBoy**
Closes #2552

### CODE REVIEW

File: src/components/List/components/VariableSizeListElementType.tsx [hunk 1]
```diff
@@ -0,0 +1,8 @@
+import * as React from 'react';
```
Comment (amje) [inline src/components/List/components/VariableSizeListElementType.tsx:3]: Missing `'use client'` directive

File: src/components/List/List.tsx [hunk 2]
```diff
@@ -558,6 +570,8 @@ export class List<T = unknown> extends React.Component<ListProps<T>, ListState<T
     private handleKeyMove(event: React.KeyboardEvent, step: number, defaultItemIndex = 0) {
         const {activeItem = defaultItemIndex} = this.state;
 
+        // console.log(activeItem);
+
```
Comment (amje) [inline src/components/List/List.tsx]: Let's delete this

File: src/components/List/components/ListItem.tsx [hunk 3]
```diff
@@ -59,7 +60,7 @@ export class ListItem<T = unknown> extends React.Component<ListItemProps<T>> {
             // eslint-disable-next-line jsx-a11y/click-events-have-key-events
             <div
                 role={role}
-                aria-selected={selected}
+                aria-selected={role === 'option' ? selected : undefined}
```
Comment (korvin89) [inline src/components/List/components/ListItem.tsx]: Let's list all the roles for which this attribute is available here https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-selected#associated_roles
