### PR TITLE
fix(DropdownMenu): fix opening from keyboard

### LINKED ISSUE #1373: DropdownMenu not opening from keyboard
https://github.com/gravity-ui/uikit/assets/3368839/f1c84998-42e9-48dd-be8c-e789b8234bb4

### PR DESCRIPTION
**Pull request by Bluepuper**
Fix #1373

### CODE REVIEW

**Review by amje — APPROVED** [review]

File: src/hooks/useActionHandlers/useActionHandlers.ts [hunk 1]
```diff
@@ -16,6 +16,7 @@ export function createOnKeyDownHandler<T>(callback?: AnyFunction) {
             callback &&
             [KeyCode.ENTER, KeyCode.SPACEBAR, KeyCode.SPACEBAR_OLD].includes(event.key)
         ) {
+            event.preventDefault();
```
Comment (ogonkov) [inline src/hooks/useActionHandlers/useActionHandlers.ts:19]: Why it is not in callback in Dropdown?

Comment (amje) [reply src/hooks/useActionHandlers/useActionHandlers.ts:19]: It's useful in every use of useActionHandlers, we want only call the callback when key is pressed, not the default behaviour of this key

**Review by ogonkov — APPROVED** [review]
okay
